travis:
  secure:
    BINSTAR_TOKEN: WSMyWXWrTYS9TV1eEzfRcHXKMBWuWf5G5KMhfetJ6fttGIa/LFPndhl9MKrpO6Tk/R3JAiBLic2YUiIAZk1lSpWnQFD35RElshpdLwp0QVnlzs730PD1gBt395E2ozPrYiu7+6vxHwxvGEeSLSH/MEetNahfR+Rk2wK1CkbxlexlJTIM3MMogEyfFglrYOA/ibljqVOlZaFthM5FlVVySwM7byYyD62tyxAAfpsAS2L1kZLte1H92b/ZQJ3mOyro35VX9kbcm87sEqj5JLlxrtmVI6N3yb/Ij9R0lmzuS1VJeTNchPmgNihlMA8kLYkAKNmMx5FCTBrMvfpM+0dyL6LM3xbxF+CD14NeycVTdpCr4cbHKmZ0OoEWbZLIV1qcX7G4y3WqQCQSLLVqzfku8euv40eMeGj7dXzeqfs8IXuSGN6Lx8LOzGf9MWdM6wKJYG0Cxx/70wsNU2FBoHI6AgfcvAFCUVc8NGVNy3aaHwthJcwo/AHAm/Agt4JmzNyzBJkFeX6rta/Eo5qbDFho/BGOYXuW+iQugXpDbpOisx45PBeito/7qVw30S72T5zQ95PV1dqbU8EG+0ExwDQPEEruFpiR94HCF+FlUEsoaOjDiWRGUKvV5/dUQmHmxJWFHuJxa3WwjtZLREEjcvWuXHKFOmifR2HaxErWJm7ZHM4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
