travis:
  secure:
    BINSTAR_TOKEN: v7NuQqg8zM3q1+0WKRIphk9QKJvfEQJqvk6/9C72ITfRz14qsYk+kAUNWDCcaoNZSYnkwxdutzeZBUvlS3Mz++xVF1mSE/O/5c+JzeXa81rKTiFTkTzz2hUM/AKdkzcaThbrgIyQWXa+AAPnnkvHqlcQORMUU5/LPnnOfeSZz//586smpmOnz/zdBgxqnAxf+UENpIsRJ4doAcE0qLCwjohmTq4n9UpGpThIFXAMw/SB/A6SMQBflQ8JfEU33cnjhK/RSyAvcob8BqrBsTYCcBrkTZpD6nnP5nVpCjF6kqUwo8bCmo9kNxstI64dJ3LcDpDoxUUKCKFHc3Y8r3oe+J3ZcsFifVlzEI/jErN03gb/EdQyr2Xn1/Uoseihkm4AneSAVVVWTFSBVUw2gZ4gXZHdGuVCvYCLlbE+o4K2xWLXzIMVoHfqguD+KavbM2trP6mmzVjB7ZH7jxTJRKqdGmlRmOaWk7UR6CHhqOIRRWSFiFg/kX3RjJLufn20ZETFZAUbXY1kMCddYKYWHKdmUqzksSZlV2oL8TNwo+c/yN3rta8F6GDAfqzyIlpYRqLL8iw4ejZSzFnQIlMcOyccbl+lZ8J6mxOcpTfe3iE9sM3ubPJ3oHWsfcPQ8hi2C9AFVcTPtiNDBoKRWCO9YoHfe34kuZaIFYuedJn6sZPZzMw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
