travis:
  secure:
    BINSTAR_TOKEN: KmvPYbgUghfHqv8rc+PN93VfmVFsLZrH86bUGX2X5wdahq5iDv3qAHDFnRkzIRLA4DMV0YPvmgfN3GW6wH14D2z0lijU+1UEjN3Sj+0UEo1FrjMjaykaVYoOrBnbp1/vODMuM+NtxY1qJLae3Z/CDc7DQQUM7zKsdjdFn5Tui4WNij72315vKxa1uKh8Xu+tOYUs2opfieddiTGT2Kb1E6TL+TabsHjoQnyfp97a0XIaOLINBh3Ao8xrbN9o0tr5raxIh6Ma7/+kMrIL/HafueiRA8Tmoz/QFUx1TFd3uB/zR4gyM736D8vHoFpLWlCIax8IJ5lYB8FpK0R2U98aoAAIZm8Lsv5sYYuC+LXEdOxLUa5PU11MMXcpOttRKJspRpq7w3jDywf3JqB0BQtiwaHUykhn9WV+Lak1gV088rvxxqEGBiNL7zR0/4LrcVQZkM6CPCLYmCv5OgiLYQfsqeMc/NbIjjYUb0ZKOor5F9kbLsf99eG2yIOKXY1SquKyG8ql0PyqhveIrGBojIZCIk0GnDa3ZpuIJW0kvVw0Ojn9CEWsgkaZcXotqczQ6lOWEeQxVhg2or7Oo7oSaLSN6canfnSgP0apQGDb2D+g0u7ZYZWD+IVliiDjfNBJz56I+wXkIQQGSXFgtIALP/yw/ELiYFxCwdgbyBFUr/Y2wo0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
